### ISSUE TITLE
Is the connection pool external yaml configuration cancelled in the new version

### ISSUE THREAD

**Issue by chinagui** [LianjiaTech/retrofit-spring-boot-starter#119]
**version**
2.3.5

**question**
Is the connection pool external yaml configuration shown below cancelled in the new version?
```yaml
  # 连接池配置
  pool:
    test1:
      max-idle-connections: 3
      keep-alive-second: 100
    test2:
      max-idle-connections: 5
      keep-alive-second: 50
```
